-- Your SQL goes here
CREATE TABLE comments (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    post_id INT UNSIGNED NOT NULL,
    parent_id INT UNSIGNED DEFAULT NULL,
    content MEDIUMTEXT NOT NULL, 
    author_id INT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    hidden_at TIMESTAMP NULL,
    locked_at TIMESTAMP NULL,
    votes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    score BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT comments_authorid FOREIGN KEY (author_id) REFERENCES users(id),
    CONSTRAINT comments_postid FOREIGN KEY (post_id) REFERENCES posts(id),
    CONSTRAINT comments_parentid FOREIGN KEY (parent_id) REFERENCES comments(id)
);