kind: pipeline
type: docker
name: default

steps:
- name: backend
  image: rustlang/rust:nightly
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
  volumes:
    - name: cargo-compilation-cache
      path: /drone/src/target
    - name: cargo-registry-cache
      path: /usr/local/cargo/registry
  commands:
  - cargo build --verbose --release --all-targets --all-features
  - cargo test --verbose --release --all-targets --all-features
  - cargo install --root /usr/local/cargo/registry cargo-tarpaulin
  - PATH=/usr/local/cargo/registry/bin cargo-tarpaulin --out Xml
  - bash <(curl -s https://codecov.io/bash) -f /target/tarpaulin/coverage.json -f ./cobertura.xml -F backend
- name: frontend
  image: node:alpine3.10
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
  commands:
  - npm i
  - npm run-script build
  - npm run-script test
  - bash <(curl -s https://codecov.io/bash) -s coverage -F frontend
- name: pre-release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
      - sha512
    files:
      - target/release/hello-rocket
    prerelease: true
    note: CHANGELOG.md
    title: RELEASE.md
  when:
    status:
      - success
    event: tag

volumes:
  - name: cargo-registry-cache
    host:
      path: /tmp/cargo/registry-cache
  - name: cargo-compilation-cache
    host:
      path: /tmp/cargo/compilation-cache
