kind: pipeline
type: docker
name: default

steps:
- name: backend
  image: rustlang/rust:nightly
  volumes:
    - name: cargo-cache
      path: /drone/src/target
  commands:
  - echo $PWD
  - cargo build --verbose --release --all-targets --all-features
  - cargo test --verbose --release --all-targets --all-features
- name: pre-release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
      - sha512
    files:
      - target/release/hello-rocket
    prerelease: true
    note: CHANGELOG.md
    title: RELEASE.md
  when:
    status:
      - success
    event: tag

volumes:
  - name: cargo-cache
    host:
      path: /tmp/cargo-cache
