kind: pipeline
type: docker
name: default

steps:
- name: backend
  image: findot/rust-node:nightly
  privileged: true
  environment:
    TEST_DB_HOST:
      from_secret: test_db_host
    TEST_DB_PORT:
      from_secret: test_db_port
    TEST_DB_ADAPTER:
      from_secret: test_db_adapter
    TEST_DB_USER:
      from_secret: test_db_user
    TEST_DB_PASSWORD:
      from_secret: test_db_password
    TEST_DB_DATABASE:
      from_secret: test_db_database
  volumes:
    - name: cargo-compilation-cache
      path: /drone/src/target
    - name: cargo-registry-cache
      path: /usr/local/cargo/registry
  commands:
  - apk add --update --no-cache libssl-dev mariadb-dev
  - cargo build --verbose --release --all-targets --all-features
  - cargo test --verbose --release --all-targets --all-features
  - cargo install --root /usr/local/cargo/registry cargo-tarpaulin
  - PATH=/usr/local/cargo/registry/bin:$PATH cargo-tarpaulin tarpaulin --out Xml
- name: frontend
  image: findot/rust-node:nightly
  volumes:
    - name: node-cache
      path: /drone/src/node_modules
  commands:
  - npm i
  - npm run-script build
  - npm run-script test
- name: coverage
  image: alpine:latest
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
  commands:
  - apk add --no-cache --update git bash curl
  - wget https://codecov.io/bash -O codecov.sh && chmod +x codecov.sh
  - bash codecov.sh
- name: pre-release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
      - sha512
    files:
      - static/*
      - target/release/hello-rocket
      - git describe --tags > release.md
    prerelease: true
    draft: true
    note: changelog.md
    title: release.md
  when:
    status:
      - success
    event: tag

volumes:
  - name: cargo-registry-cache
    host:
      path: /tmp/cargo/registry-cache
  - name: cargo-compilation-cache
    host:
      path: /tmp/cargo/compilation-cache
  - name: node-cache
    host:
      path: /tmp/node-cache