version: "3.3"

services:
  server:
    build: .
    ports: 
      - 8000:8000
    volumes:
      - .:/usr/src/app
      - registry-cache:/usr/local/cargo/registry
    depends_on:
      - db
    links:
      - db

  db:
    image: mariadb:latest
    restart: always
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
      MYSQL_ROOT_PASSWORD: hypersecretpassword
      MYSQL_DATABASE: test_rocket

volumes:
  registry-cache:
  database: