version: "3.3"

services:
  server:
    build: .
    ports: 
      - 8000:8000
    volumes:
      - .:/usr/src/app
      - registry-cache:/usr/local/cargo/registry
    depends_on:
      - db
    links:
      - db
    environment:
      INTERFACE: 0.0.0.0
      DB_PROVIDER: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: testuser
      DB_PASSWORD: testpassword
      DB_DATABASE: test_rocket
      DATABASE_URL: mysql://testuser:testpassword@db/test_rocket
      JWT_SECRET: KupnibWushCeroicDabbadBew

  db:
    image: mariadb:latest
    restart: always
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
      MYSQL_ROOT_PASSWORD: hypersecretpassword
      MYSQL_DATABASE: test_rocket

volumes:
  registry-cache:
  database: