[global.databases]
mariadb_test = {url="mysql://testuser:testpassword@localhost/test_rocket"}

[development]
address = "localhost"
port = 8000
# workers = [number of cpus * 2]
keep_alive = 5
log = "normal"
# secret_key = [randomly generated at launch]
limits = { forms = 32768 }

[production]
address = "127.0.0.1"
port = 8000
# workers = [number of cpus * 2]
keep_alive = 5
log = "critical"
# secret_key = [randomly generated at launch]
limits = { forms = 32768 }