@startuml db_mdl

hide circle
hide empty members

' entity Entity {
'    * identifying_attribute
'    --
'    * mandatory_attribute
'    optional_attribute
' }

' ' zero or one
' A |o--o| B

' ' exactly one
' C ||--|| D

' ' zero or many
' E }o--o{ F

' ' one or many
' G }|--|{ H

entity User {
  * user_id
  --
  * email 
  * firstname 
  * lastname
  * password
  * adress_id (FK)
  * ...
}

entity Address {
  * adress_id
  --
  * street
  * number
  * city
  * zipcode
  * country
  * phone
}



entity UpDownVote {
  * user_id (FK)
  * post_id (FK)
  --
  * created_on
  * is_up
}

entity TagSubscription{
  * user_id (FK)
  * label (FK)
}

entity Tag {
  * label
}

entity Post {
  * post_id
  --
  * title
  * type
  * content
  * created_on
  * vote_count
  * user_id (FK)
}


entity VotingPost {
  * post_id (FK)
  --
  * end_date
}

entity TagPost {
    * post_id (FK)
    * label (FK)
}

entity UserVote {
  * post_id (FK)
  * user_id (FK)
  --
  * answer (FK)
  * created_on
}

entity VotingAnswer{
  * post_id (FK)
  * answer
}

entity Faculty  {
  * fac_id
  --
  * name
  * email
  * adress_id (FK)
}

Address ||--o| User


Faculty }|--o{ User
Faculty |o--|| Address


User ||-o{ Post : Write
User ||--o{ UpDownVote 
Post ||--o{ UpDownVote 

Post ||--o| VotingPost
VotingAnswer}|-|| VotingPost

User  ||--o{ UserVote
VotingAnswer ||--o{  UserVote 

TagSubscription }o-|| User
TagSubscription }o-|| Tag

Tag  ||-|{  TagPost
Post ||-|{  TagPost
@enduml
